- name: install mariadb
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - mariadb
  - mariadb-server
  register: install

- name: install supervisor configuration
  copy:
    src: mariadb.ini
    dest: /etc/supervisord.d/mariadb.ini
  register: supervisor

- name: start mariadb service
  supervisorctl:
    name: mariadb
    state: present

- name: database setup
  shell: mysql_install_db
  when: install.changed

- name: change owner of /var/lib/mysql
  file:
    path: /var/lib/mysql
    owner: mysql
    recurse: yes

- name: restart mariadb
  supervisorctl:
    name: mariadb
    state: restarted
  when: install.changed

