- name: install mariadb
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - mariadb
  - mariadb-server
  register: install

- name: database setup
  shell: mysql_install_db
  when: install.changed

- name: change owner of /var/lib/mysql
  shell: chown -R mysql /var/lib/mysql
  when: install.changed

- name: install supervisor configuration
  copy:
    src: mariadb.ini
    dest: /etc/supervisord.d/mariadb.ini
  register: supervisor

- name: start mariadb
  supervisorctl:
    name: mariadb
    state: started

- name: reload supervisor
  supervisorctl:
    name: mariadb
    state: restarted
  when: install.changed or supervisor.changed

